name: Android Build Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build Project
        # Memory Optimization: Heap size kam karke crash roko
        run: |
          chmod +x ./gradlew
          ./gradlew :core:app:assembleDebug -x validateSigningDebug \
          -Dorg.gradle.jvmargs="-Xmx1024m -XX:+UseParallelGC" \
          --no-daemon --max-workers=2
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: core/app/build/outputs/apk/debug/*.apk
