name: Android Build Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Android Code Studio
        # Memory limit aur worker count ko control kiya hai taaki RAM crash na ho
        run: |
          chmod +x ./gradlew
          ./gradlew :core:app:assembleDebug \
          -x validateSigningDebug \
          --no-daemon \
          --parallel \
          --max-workers=2 \
          -Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxMetaspaceSize=512m"

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: AndroidCodeStudio-Build
          path: '**/build/outputs/apk/debug/*.apk'
          if-no-files-found: error
