name: Build Android Code Studio

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Default checkout ko band karke, manual git sync karenge
      - name: Checkout Code
        run: |
          git init
          git remote add origin https://github.com/${{ github.repository }}
          git fetch origin ${{ github.ref }}
          git reset --hard FETCH_HEAD
          git submodule update --init --recursive --force

      # Step 2: Java Setup
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Gradle Build
      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew :core:app:assembleRelease
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          KEY_ALIAS: "AndroidCS"

      # Step 4: Upload
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-code-studio-apk
          path: core/app/build/outputs/apk/release/*.apk
        if: always()
